spring.application.name=pr
github.token=${GITHUB_TOKEN}
github.api.base.url=https://api.github.com
ollama.base-url=http://localhost:11434
ollama.model=llama3.2
github.webhook.secret=${GITHUB_WEBHOOK_SECRET:placeholder}
logging.level.io.netty.resolver.dns.macos=OFF
